version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - .:/usr/src/app:cached
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: pipenv run python manage.py runserver 0.0.0.0:8000
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mysql-db
volumes:
  db-data: